App\Entity\Location:
    properties:
        city:
            - NotBlank: { groups: [new] }
            - Length: { min: 3, groups: [new, edit] }
        country:
            - NotBlank: { groups: [new, edit] }
        latitude:
            - NotBlank: { groups: [new, edit] }
            - Range: { min: -90, max: 90, groups: [new, edit] }
        longitude:
            - NotBlank: { groups: [new, edit] }
            - Range: { min: -180, max: 180, groups: [new, edit] }
